import { Geist, Geist_Mono, Lato } from "next/font/google"; // Lato ফন্টটি import করা হলো
import "./globals.css";
import Header from "@/components/Navbar";
import AppFooter from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Lato ফন্ট কনফিগার করা হলো
const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700', '900'], // প্রয়োজনীয় weight গুলো যোগ করা হয়েছে
  variable: '--font-lato',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // lato.variable এখানে যুক্ত করা হলো 
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
      >
        <Header />
        {children}
        <AppFooter />
      </body>
    </html>
  );
}
